### ISSUE TITLE
.fountain support 

### ISSUE THREAD

**Issue by philippnagel** [uranusjr/macdown#231]
Hi, 

I write screenplays (besides code) and a great way to do that is using [Fountain](http://fountain.io).

Fountain is a markup language inspired by Markdown, designed to make writing screenplays as convenient as possible. 

Currently the support trough open source applications is quite thin. I really like Macdown and thought a support for .fountain might be a great fit for this project. 

Would that be interesting for some of you?

**Comment by bronzehedwick** [comment]
+1

**Comment by uranusjr** [comment]
Unfortunately I’ll have to turn this down. From the spec it seems to differ quite a lot from Markdown, despite sharing certain attributes. Supporting it would be much out of the scope of MacDown, which I would like to be not much more than a simple Markdown editor.

With that said, it isn’t very difficult to fork MacDown, and swap out the backend to render Fountain input instead of Markdown. There’s already work to make an AsciiDoc version of MacDown; [Fountain officially supports a nice library that works in Xcode](https://github.com/nyousefi/Fountain) (even with CocoaPods releases!), and the examples seems pretty well written.

I am pretty stretched already to start another new project (especially for something I don’t use personally), but if someone is interested in this I would be happy to answer questions regarding MacDown’s internal implementation details, and/or help on other things is possible.
