### ISSUE TITLE
Enabling line numbers for fenced code blocks

### ISSUE THREAD

**Issue by motine** [uranusjr/macdown#246]
first, thanks for the great editor. I have been using Mou for quite a while, but MacDown was quite a revelation for me.

Sometimes I need line numbers. Since Prism supports it, I would love you to add support too.
I could think of some kind of parameterization of the fenced code (e.g. a # after the language specifier) like so: ```javascript#

**Comment by uranusjr** [comment]
The current problem is that we currently lacks a way to parse options (other than language names) inside code blocks (hoedown/hoedown#132). But I think I can make some improvements to make this happen. :)

**Comment by motine** [comment]
If I would solve the issue, the way described above (without changing hoedown) and rather screwing with the language name like `ruby#`, would you be inclined to add that pull request? This solution would not scale well and not be very elegant, so I better ask before...

**Comment by uranusjr** [comment]
I will, honestly, and you already mentioned my reasons. But first of all, is there any reason to use this particular syntax? Maybe it would be better to make this a global preference instead, under the *Syntax highlighting in code blocks* option. This would make the implementation pretty straightforward and usage simple (“just tick the box”). The downside is that it would be impossible to make blocks with and without line numbers co-exist. But I don’t think that is a common pattern (correct me if I’m wrong), and, maybe more importantly, it is not easy to configure Prism to render things that way.

So, if it is reasonable to have this as a global preference (instead of on a per-block basis), I’ll implement that instead.

**Comment by motine** [comment]
Actually, you are totally right – a global setting would be more than sufficient. I would appreciate that.

Side note: I did not want to pressure the development. I just wanted to offer help, because I really love what you have done with this project. So, rock on! You are doing a great job.

**Comment by uranusjr** [comment]
Thanks! And don’t worry—enabling Prism plugins is one of many things I have intended to work on for some time. A little pressure is good for getting things done sometimes. ;)

**Comment by uranusjr** [comment]
Fixed in #247.
