### ISSUE TITLE
Automatic refreshes from the filesystem?

### ISSUE THREAD

**Issue by ohthetrees** [uranusjr/macdown#257]
Many mac programs will update the document window when the underlying file is changed by another program. As an example, an open bbedit text document will reflect changes made in another editor almost instantly. Macdown does not update when the underlying file changes, and there is potential for data loss when changes are made to a document open in both Macdown and  another editor (say,  bbedit).

It may sound silly to have the document open in Macdown and another place, but here is a real life example: I often have a document open in Macdown for continuous editing, then do a git pull. The underlying document is updated by git, but Macdown doesn't display that change. Then when I edit and save the document in Macdown, it overwrites any changes that may have come along in the git pull. 

Hope I'm making myself clear!

Thanks,
Cedar

**Comment by uranusjr** [comment]
This will be a requirement in the future, actually, since we’re planning to support TextBundle (#135). There are others looking for the same thing, too (e.g. #48). The implementation is trickier than I thought, though, and I’m currently prioritise other things first. :(

Closing this as a duplicate to make the issue list stays tidy and to centralise the discussion.
