### ISSUE TITLE
Bold nested inside italics doesn't render correctly

### ISSUE THREAD

**Issue by colindean** [uranusjr/macdown#260]
When I write 

    *what **the** crap*

it renders the bold, but not the italics, and leaves the asterisks in place.

![screen shot 2015-02-03 at 17 09 16](https://cloud.githubusercontent.com/assets/197224/6030727/7ea924b4-abc7-11e4-8362-b22e98327a2f.png)

Using Version 0.4.2 (578).

**Comment by colindean** [comment]
Mou handles it as I'd expect:

![screen shot 2015-02-03 at 17 11 16](https://cloud.githubusercontent.com/assets/197224/6030753/b8662e5e-abc7-11e4-8d22-6df9b2acd874.png)

But Github doesn't:

**what *the* crap**

*what **the** crap*

![screen shot 2015-02-03 at 17 11 51](https://cloud.githubusercontent.com/assets/197224/6030760/c7c63376-abc7-11e4-9084-0f68c97b66fe.png)

**Comment by colindean** [comment]
[Online Kramdown Editor](http://kramdown.herokuapp.com/) gets it:

![screen shot 2015-02-03 at 17 13 41](https://cloud.githubusercontent.com/assets/197224/6030796/09766052-abc8-11e4-8080-155964768d1b.png)

**Comment by uranusjr** [comment]
These nested markups are always problematic in Markdown. There are discussions at the issue tracker of Hoedown (which is MacDown’s main Markdown backend) about similar issues, too, like hoedown/hoedown#78 and hoedown/hoedown#138. There are people working on it, but this will require quite some rewriting of logic, which takes time.

Since this only happens with the renderer (the syntax highlighter works as expect), I’ll close this so discussion can be centralised at the aforementioned Hoedown issues. It does not mean that we won’t fix this.
