### ISSUE TITLE
enhancement: export functionality

### ISSUE THREAD

**Issue by frankis** [uranusjr/macdown#264]
I just found http://johnmacfarlane.net/pandoc/index.html which provides some very interesting options to convert / export documents in various very useful formats.

I highly recommend reviewing this and considering it as a future feature making macdown a must have for anyone writing on-/offline content.

**Comment by uranusjr** [comment]
(I remember having a similar conversation on this with someone else somewhere, but can’t seem to find the post.)

Pandoc is a *hugh* project, and has lots of dependencies (some of them optional and only needed if you want to use certain functionalities). It not honestly not realistic to bundle everything in MacDown, which I want to be a compact and slim editor. The export thing is a plus, but is not, and probably never will be of high priority. Implementing even half of the formats Pandoc supports would take too much of my time, and I’d rather spend them to improve the editor. You can just use Pandoc if you really want to export to those formats, after all.

With that said, IIRC the conclusion we (some other person and I who had the earlier discussion) reached is that it would probably be better if this can be implemented as a plugin. You can install Pandoc if you want, and MacDown can provide a thin GUI wrapper to let you use Pandoc on your documents.

But the plugin system is also a thing yet to be implemented. If only I have unlimited time. :(

I’m closing this as wontfix since we won’t really implement what Pandoc offers. But the plugin solution is on my todo list.
