### ISSUE TITLE
Underscores in hyperlink labels are rendered improperly in Preview

### ISSUE THREAD

**Issue by ericdorsey** [uranusjr/macdown#352]
If you have this hyperlink label (that has underscores in it) in your Markdown file:

``` 
[test_another_folder/another_folder_instruction_1.md](test_another_folder/another_folder_instruction_1.md)
```

It should render like this:
> test_another_folder/another_folder_instruction_1.md

But in MacDown it instead renders like this:
> test*another*folder/another*folder*instruction_1.md

![screen shot 2015-04-17 at 8 39 48 pm](https://cloud.githubusercontent.com/assets/140428/7213634/8c3f88e8-e542-11e4-9684-bd5e2c58ef3f.png)

Screenshot attached.

**Comment by uranusjr** [comment]
This is expected. All mainstream Markdown specifications allow markups in the link text, and underscores here are correctly recognised as intra-word emphases, as in the original Markdown spec.

[Mainstream Markdown engine outputs](http://johnmacfarlane.net/babelmark2/?text=%5B%2Fsome%2Fwhere%2Finside_your_computer%5D(%2Fsome%2Fwhere%2Finside_your_computer))

Both behaviours are common. We will conform to CommonMark in the future (#149), so this will be adjusted. But we are not (for now), so this is not considered as a bug.

I would suggest using inline code spans as a solution here, since you probably should do that anyway:

    [`test_folder/test_markdown.markdown`](test_folder/test_markdown.markdown)

**Comment by ericdorsey** [comment]
Interesting; thanks for the feedback. I am glad things are going the CommonMark direction (which is also the way GitHub renders it).
