### ISSUE TITLE
Support GitHub Flavored Markdown

### ISSUE THREAD

**Issue by NickVolynkin** [uranusjr/macdown#382]
This is a reature request.
GitHub uses it's own rules of markdown rendering, called [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/).
It includes, for example, rendering checkboxes.
```
- [ ] Option
```
Becomes:
![screen shot 2015-05-27 at 14 22 48](https://cloud.githubusercontent.com/assets/8015154/7831816/885f508c-0473-11e5-9af2-581ba43528ef.png)

As I write for GitHub a lot, I would be happy to have support for GFM in MacDown.

**Comment by uranusjr** [comment]
The checkbox thing is already (partially) supported. See #225. The behaviour can be very similar to GFM if you set the right preferences in both “Markdown” and “Rendering” groups. There are some minor differences (mostly cosmetic), but should be good enough for normal uses.

Close as duplicate since the main request (task list) is already supported, and differences between GFM and MacDown’s parser are already addressed by other tickets.

**Comment by NickVolynkin** [comment]
Thank you, I've found it.
