### ISSUE TITLE
Crash when opening latest update

### ISSUE THREAD

**Issue by fbara** [uranusjr/macdown#398]
I just updated to 0.4.5.  Every time I try to open the app, it crashes.  I deleted the app complete and reinstalled 0.4.5, the same thing happened.  Here's the text from the crash report:
```
Process:               MacDown [46835]
Path:                  /Users/USER/Downloads/MacDown.app/Contents/MacOS/MacDown
Identifier:            com.uranusjr.macdown
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MacDown [46835]
User ID:               501

Date/Time:             2015-06-28 10:04:37.744 -0500
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        E9EA0390-2714-870C-D108-6F1150BA1446

Sleep/Wake UUID:       36C5F9B0-FB39-4727-9DBF-C2DCB5A27501

Time Awake Since Boot: 40000 seconds
Time Since Wake:       4200 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/USER/Downloads/MacDown.app/Contents/MacOS/MacDown
  Reason: image not found

Binary Images:
    0x7fff6eb04000 -     0x7fff6eb3a837  dyld (353.2.1) <65DCCB06-339C-3E25-9702-600A28291D0E> /usr/lib/dyld
    0x7fff8b529000 -     0x7fff8b85afff  com.apple.Foundation (6.9 - 1153.20) <F0FF3A5D-C5B7-34A1-9319-DE1EF928E58E> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
```

**Comment by sorra** [comment]
Me, too.

Process:               MacDown [20499]
Path:                  /Applications/MacDown.app/Contents/MacOS/MacDown
Identifier:            com.uranusjr.macdown
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MacDown [20499]
User ID:               501

Date/Time:             2015-06-28 23:24:38.472 +0800
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        4C03A4CD-6F52-D990-07F0-A94153D6FF3B

Sleep/Wake UUID:       328A1DDC-6C6D-41DB-AE5A-00F9B1AF1B68

Time Awake Since Boot: 160000 seconds
Time Since Wake:       11000 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Applications/MacDown.app/Contents/MacOS/MacDown
  Reason: image not found

Binary Images:
    0x7fff6dc4c000 -     0x7fff6dc82837  dyld (353.2.1) <65DCCB06-339C-3E25-9702-600A28291D0E> /usr/lib/dyld
    0x7fff8af31000 -     0x7fff8b262fff  com.apple.Foundation (6.9 - 1153.20) <F0FF3A5D-C5B7-34A1-9319-DE1EF928E58E> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

Model: MacBookPro11,3, BootROM MBP112.0138.B14, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.4f4 15601, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: Internal Memory Card Reader
USB Device: G90 Optical Gaming Mouse
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by uranusjr** [comment]
I messed up some dependencies in the last update. Please download the fix [here](https://github.com/uranusjr/macdown/releases/tag/v0.4.5.1).

Sorry for the inconvenience.
