### ISSUE TITLE
I can't get preview using Macdown

### ISSUE THREAD

**Issue by Andrew-liu** [uranusjr/macdown#403]
When I open the editor, It can't get any Markdown preview on the preview pane.

I have a picture to describe the problem.

![图示](http://ww2.sinaimg.cn/large/ab508d3dgw1etohg5qq30j21kw0hi75q.jpg)

**Comment by uranusjr** [comment]
Do you check “Update preview automatically as you type” in the preferences? And what happens if you press cmd-R to render manually?

If both of the above fail, could you 

1. Open a terminal and execute the following command:

        defaults write com.uranusjr.macdown WebKitDeveloperExtras -bool true

2. Re-launch MacDown.

3. Right click in the preview pane and select “Inspect Element”

4. Click on the top-most `<html>` line (should be the second line) in the pop-up window, right click, and select “Copy as HTML”.

5. Paste the content somewhere.

**Comment by Andrew-liu** [comment]
Thanks, I have solve this problem using your methods.

I like this Markdown editor. Thanks!
