### ISSUE TITLE
MacDown crashing instantly upon launch in 10.9.5

### ISSUE THREAD

**Issue by jackmaney** [uranusjr/macdown#420]
https://gist.github.com/jackmaney/4c5360255d5f43391567

**Comment by uranusjr** [comment]
Duplicate to #344. I’ll release the bugfix this weekend.

**Comment by jackmaney** [comment]
Strangely enough, uninstalling (via removing `/Applications/MacDown.app`) and installing via `homebrew cask` did the trick. Not sure why.

**Comment by uranusjr** [comment]
That makes sense (sort of), since this is caused by some resource lookup code. I made some assumptions about resources being at certain paths (because they should), but for some reason the lookup can still fail on some setup. Re-installing the app effectively resets all bundled resources.

And I totally forgot about promising a new release the past weekend! Doing it not.
