### ISSUE TITLE
Allow <!--- This is a comment which will not appear in the rendered page --->

### ISSUE THREAD

**Issue by blackslate** [uranusjr/macdown#439]
It would be good to have two ways of creating comments:

1. Comments in the  which will appear in the output file
2. Comments for the MacDown author's eyes only, which will not appear in the output.

Here's a [discussion on Stack Overflow](http://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax) about this.

**Comment by uranusjr** [comment]
There is already limited support. The comments should be on their own line, with a blank line before them.

    Some text.

    <!-- This is a comment. -→

    Some more text

    <!-- Text can follow the comment, as long as they’re in different lines. -→
    More text

    But the following line will be rendered.
    <!-- This is NOT a comment. -→

The limitation is caused by difficulties distinguishing comments from intended text input, since Markdown does not support native comments. The rules might be revised (and improved) in the future, but not in the short term. I hope this is enough for your use.

Closing as wontfix.

**Comment by blackslate** [comment]
Thanks for the explanation.
