### ISSUE TITLE
When making a list, the last item displays as H2 until something is typed

### ISSUE THREAD

**Issue by Joshfindit** [uranusjr/macdown#451]
![macdown list item bug](https://cloud.githubusercontent.com/assets/1937155/10170969/eedf7afc-66ad-11e5-8928-d480abddcf94.gif)

Note, that using 'alternate' H2 ( https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers ) syntax would make the following valid:

    List item 2
    ----

And Macdown respects this by changing how it's displayed on the editor side
![screenshot 2015-09-29 13 05 37](https://cloud.githubusercontent.com/assets/1937155/10170346/d170387e-66aa-11e5-8bce-a0b6b1dc8ed3.png)

Expected behaviour:

A single `-`, `*`, or `=` is rendered as-is, not rendered as though it were `----`, `****`, or `====`

**Comment by uranusjr** [comment]
This is a known behavioural mismatch between the editor highlighting and the actual HTML renderer. It can be fixed by standardising CommonMark (#149). But we’ll need to get Hoedown v4 working first.

This will be fixed indirectly. I’m closing so that all related discussions can be kept in one place.
