### ISSUE TITLE
Match Jekyll regex pattern for YAML frontmatter

### ISSUE THREAD

**Issue by adunning** [uranusjr/macdown#469]
The [Jekyll code](https://github.com/jekyll/jekyll/blob/7c4f319442b6b7a457d35cef2fc1b7a480b30850/lib/jekyll/document.rb#L9) uses a slightly different regex pattern from the one [MacDown recognizes](https://github.com/uranusjr/macdown/blob/74c04167153f41556971b570c0dfce3db6204def/MacDown/Code/Extension/NSString%2BLookup.m#L59), allowing the block to close with `...`; could this be updated, please?

(Thanks for all your work on this!)

**Comment by masukomi** [comment]
I'm not sure why Jekyll added that, it seems... well it seems inconsistent and silly BUT IF the regexp is going to be updated at all it should probably be updated to support that, TOML frontmatter, and JSON frontmatter. All are [supported by Hugo](https://gohugo.io/content/front-matter/) and I wouldn't be surprised if the idea has spread to other static blog systems because... well, YAML's kinda crap. ;)

maybe that would justify a separate issue, but it makes sense to muck with it all at once so I'm throwing the idea in here.

**Comment by adunning** [comment]
It's part of the [YAML spec](http://www.yaml.org/spec/1.2/spec.html#id2800401), actually. I don't personally use anything apart from YAML, but I can certainly see broader support being appreciated.

**Comment by uranusjr** [comment]
Hmm, I honestly wasn’t aware of the `...` syntax. Since it is a standard syntax, I’ll fix that.

BTW I personally enjoy writing my configs in YAML since it is way more readable than other markup languages (e.g. XML and JSON). But it really is a pain having to implement so many arbitrary features. I would be so happy if there is a standard YAML subset—let’s call it YAMLite—that supports a little as JSON does with YAML’s syntax.

**Comment by Jmuccigr** [comment]
Thanks to @adunning for raising this here. It looked to me like Jekyll did NOT support the dots method, mainly because I was assuming that MacDown's behavior showed that and a couple of threads over at Jekyll seemed to say that too.

The dots do seem to be the YAML standard. I'm not sure I'd say it's any more arbitrary than anything else.

**Comment by Jmuccigr** [comment]
Tried my hand at fixing this. Here's the PR. #471
