### ISSUE TITLE
When formatting a blockquote, text gets lost

### ISSUE THREAD

**Issue by bartv42** [uranusjr/macdown#492]
When I select multiple paragraphs and select Format > Blockquote, I lose a few words at the end of the last paragraphs.

**Comment by uranusjr** [comment]
Fixed in 565e638

**Comment by uranusjr** [comment]
BTW to work around this before the fix is released: When you make a selection, *do not* select the whole thing, but leave out of few characters at the last line. Any partially selected line will be converted to blockquote, so this shouldn’t affect the output, but will prevent the bug from being triggered. Yes I know this is crazy.

**Comment by bartv42** [comment]
The work around doesn't seem to work for me, but I can live with it knowing that it'll be fixed in the next release. Thanks!
